# Generated by Django 2.2 on 2019-06-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_squashed_0023_auto_20190607_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['performance_start', 'show_date']},
        ),
    ]
