# Generated by Django 2.2 on 2019-06-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_auto_20190610_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-show_date', '-performance_start']},
        ),
    ]
