# Generated by Django 2.2 on 2019-06-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0006_auto_20190613_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='induction',
            name='show_stop',
            field=models.ManyToManyField(blank=True, help_text='Please indicate the things that <strong>occur during the show</strong>', to='stuff.ShowStop'),
        ),
    ]
