# Generated by Django 2.2 on 2019-06-14 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0009_auto_20190615_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 0, 59, 51, 169065)),
        ),
    ]
