# Generated by Django 2.2 on 2019-06-15 00:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0010_auto_20190615_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logreport',
            name='company_name',
            field=models.ForeignKey(blank=True, default=None, help_text='If this log entry is to do with a company, select which one.', null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Company'),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 1, 0, 57, 519852)),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='show_name',
            field=models.ForeignKey(blank=True, default=None, help_text='If this log entry is to do with a show, select which one.', null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Show'),
        ),
    ]
