# Generated by Django 2.2 on 2019-06-15 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0012_auto_20190615_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 2, 20, 30, 239440)),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='subject_name',
            field=models.CharField(blank=True, help_text='Who, if anyone, is this report about?', max_length=100),
        ),
    ]
