# Generated by Django 2.2 on 2019-06-15 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0013_auto_20190615_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 2, 24, 31, 662556)),
        ),
    ]
