# Generated by Django 2.2 on 2019-06-15 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0014_auto_20190615_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logreport',
            options={'ordering': ['-report_date']},
        ),
        migrations.AlterField(
            model_name='logreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 3, 5, 12, 691967)),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='report_text',
            field=models.TextField(help_text='Festival log entries are only visible to the management team, and will be kept confidential where necessary. Please provide as much detail as possible.'),
        ),
    ]
