# Generated by Django 2.2 on 2019-06-15 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0018_auto_20190615_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayreport',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 15), unique=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 3, 28, 25, 672944)),
        ),
    ]
