# Generated by Django 2.2 on 2019-06-15 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0021_auto_20190615_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 15, 2, 29, 16, 659579, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 3, 29, 16, 661899)),
        ),
    ]
