# Generated by Django 2.2 on 2019-06-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0022_auto_20190615_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayreport',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='report_date',
            field=models.DateTimeField(),
        ),
    ]
