# Generated by Django 2.2 on 2019-06-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0023_auto_20190615_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayreport',
            options={'ordering': ['-date']},
        ),
    ]
