# Generated by Django 2.2 on 2019-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0024_auto_20190615_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='microphones',
            field=models.IntegerField(default=0, help_text='How many microphones are being used?'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='projector_screen',
            field=models.BooleanField(default=False, help_text='Does this show require a projector screen?'),
        ),
    ]
